
version: '3.8'
services:
  builder:
    image: lechgu/scala-lab
    volumes:
    - ./tsi:/tsi
    working_dir: '/tsi'
  
  master:
    build: .
    ports:
      - 7077:7077
      - 8080:8080
    command: /spark.sh 0

  worker:
    build: .
    ports:
      - 8081:8080
    command: /spark.sh 1


 