
version: '3.8'
services:
  builder:
    image: lechgu/scala-lab
    volumes:
    - ./tsi:/tsi
    working_dir: '/tsi'
  
  master:
    build: .
    ports:
      - 7077:7077
      - 8080:8080
    command: /spark.sh 0

  worker:
    build: .
    command: /spark.sh 1

  notebook:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/notebooks
      - ./tsi:/tsi
    working_dir: '/notebooks'
    command: /jupyter.sh


 